name: Test Pull Request

on:
  pull_request:
    branches: ["master", "test"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: finance
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Run Docker Container
        run: docker run -d --name finance -p 3000:80 finance
      - name: Stop Docker Container
        run: docker stop finance
      - name: Remove Docker Container
        run: docker rm finance
